### ISSUE TITLE
Peer Review from Stat Squad Team

### ISSUE THREAD

**Issue by durgagubbala86** [INFO-526-FA24/project-2-datawaves#1]
1. Team:
    Prasanth Gubbala, Prudhvi Kandregula, Xenia De Gracia, Rishab RK
    
2. Describe the goal of the project.
    The project goal is clear and well-defined, focusing on visualizing AR models and demonstrating the effect of parameters on time series patterns.
    
3. Describe the data used or collected.
    The data generation plan is well-explained, using arima.sim() to create synthetic data for specific AR models. However, examples of real-world applications or scenarios could make the approach more relatable.
    
4. Describe how the research question will be answered, e.g. what approaches / methods will be used.
    The project proposes using ggplot2 for static visualizations and a Shiny app for interactive exploration. The AR models are broken down into variations, such as random walk, oscillatory, and complex patterns, allowing for a thorough exploration of AR parameters and behaviors.
     
5. Is there anything that is unclear from the proposal?
    The proposal is generally clear, but it would be helpful to explain how the chosen parameter values (like specific positive or negative coefficients) will impact each type of AR model. 

6. Provide constructive feedback on how the team might be able to improve their project.
     Consider expanding the introduction to briefly mention real-world contexts where different AR behaviors are observed, like economic trends or weather patterns. This would highlight the relevance of the AR model types.

7. What aspect of this project are you most interested in andwould like to see highlighted in the presentation.
    The interactive Shiny app is a standout feature. Seeing how users can manipulate parameters and observe changes in real-time would be very engaging. A live demonstration of the app would be a great addition to the presentation.

8. Provide constructive feedback on any issues with file and/or code organization.
    nothing specific and file structure also looks good.

9. (Optional) Any further comments or feedback
     complete proposal looks so clear but only thing I noticed AR model explanation would be more understandable to the audience if you take real time example addition to the existing plan, its upto you based on time constrains. overall proposal looks great.
     
     
Thanks & Regards,
Team - Stat Squad

**Comment by iam-ajeetsingh** [comment]
Thank you for your insightful peer review and valuable feedback on our project proposal. We've carefully considered your suggestions and have incorporated them in our proposal. We have added the Real-World Applications of AR Model into our proposal. We appreciate your time and contributions. Closing this issue now.

**Comment by libin-n-g** [comment]
Fixed in 7a6aa0358da559b5ae8833e6bc823e0f3a49eea6
