### ISSUE TITLE
Review by Visual Voyagers

### ISSUE THREAD

**Issue by bhaskar-237** [INFO-526-FA24/project-2-datawaves#16]
Strength: The topic chosen, Auto-regression is a very interesting topic with important applications. 

Weaknesses: Might consider spacing out text and graphs more evenly. Explain with more coherency, especially the technical part and incorporate how it will apply to real world problems.

**Comment by iam-ajeetsingh** [comment]
Thank you for the feedback. We have made the requested modifications to the poster.
