### ISSUE TITLE
Review from DreamJobs

### ISSUE THREAD

**Issue by Lucifer970901** [INFO-526-FA24/project-2-datawaves#17]
overall looks good, try to add more usecases so that each of the different AR models can be distinguished.

**Comment by Naveenksaragadam** [comment]
You’ve done a phenomenal job with the poster! The idea is fantastic, and I really commend you for simplifying such a complex topic—kudos to the entire team.

There are a few points that could add even more value. I suggest providing more context about the model and emphasizing the necessity of creating it before diving into the mathematical details (perhaps start with a hook to engage the audience). You could shorten the mathematical and reference sections and shift the focus toward providing interesting insights and discussing the future state of the model.

Great work overall, and good luck!

**Comment by NavyasreeMadhu14** [comment]
Thank you so much for your valuable feedback. We will work on improving our poster based on your suggestions.
