### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by gr98765** [INFO-526-FA24/project-2-datawaves#2]
1.Team name: Visual Voyagers
Team members: Gaurangi Raul, Bhaskar Bijoy Kashyap, Viren Sasalu, Tushar Vimal. @gr98765 @bhaskar-237 @virensasalu @tusharvimal

2. Goal of the project: Through visualization and interactive tools, the project aims to provide insights into how AR models, specifically AR(1), AR(2), AR(3) and varying parameters influence the time series patterns.

3. Describe the data used:
The data will be synthetically generated using the arima.sim() function in R to simulate AR processes with controlled parameters. 

4. Describe how the questions/approaches will be used:
The project uses various configurations in AR models by visualizing line graphs and autocorrelation plots to see how the data behaves, including oscillatory patterns, positive/negative correlations, and random walks. There is also use of shiny app for interactive plots to provide real time updates.

5. Is there anything unclear:
The overall approach is clearly defined, however it might be helpful to clarify

-The specific parameter ranges to be tested for each AR model.
-If there will be any statistical testing or model performance evaluation included, or if the project will focus solely on visualization and qualitative analysis.

6. Constructive feedback:
Consider adding a brief background on the practical implications of AR models to connect theory with real-world applications.
Also could be helpful to provide baseline comparisons, like a visual for white noise, to highlight differences in patterns more effectively.

7. what aspect of the project are you most interested and looking forward to see highlighted:
The interactive Shiny app is highlight of the project.It will be exciting to see how dynamic visualizations allow to explore the effects of different AR parameters on time series patterns and how there is a contrast between the AR models.

8. Feedback on issues:
Everything is clear and looking forward the use of shiny app.

**Comment by iam-ajeetsingh** [comment]
We appreciate your insightful peer review and the valuable feedback you've provided on our project proposal. After careful consideration, we've integrated your suggestions into our updated proposal. 
Thank you for your time and contributions. We are now closing this issue.

**Comment by libin-n-g** [comment]
Fixed in 7a6aa0358da559b5ae8833e6bc823e0f3a49eea6
