### ISSUE TITLE
Peer Review of iShowcase Poster by Team Insight Decoders

### ISSUE THREAD

**Issue by hemabk** [INFO-526-FA24/project-2-datawaves#20]
Hello Team Datawaves,

Strengths:
1) The plot is unique and visually engaging, drawing attention effectively.
2) The use of synthetic data adds an innovative aspect to the project.

Weaknesses:
1) The poster contains excessive text, which may distract from the visual elements.
2) The graph requires significant explanation, reducing its immediate interpretability.

**Comment by NavyasreeMadhu14** [comment]
Thank you for your valuable feedback. We consider reducing the excessive text and improving the overall design of the poster.
