### ISSUE TITLE
Project Report feedback by ViZit

### ISSUE THREAD

**Issue by SumelRattan** [INFO-526-FA24/project-2-datawaves#22]
Hi, 
Here is our team's feedback on your project report.

- A complex topic is well-explained using clear textual descriptions.
- Consider incorporating more visualizations to enhance storytelling and audience engagement.

Let me know, if you need any clarification/suggestions.

**Comment by NavyasreeMadhu14** [comment]
Thank you so much for your valuable feedback. We will add your suggestions to the poster.
