### ISSUE TITLE
Instructor review 

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-datawaves#3]
Hello team Datawaves -  

Overall, your proposal indicates that you are set up for a success. You have a data set that will be able to answer the research questions through the proposed analysis and visualizations. Keep in mind the audience is the Info Science students - not everyone will be able to understand some of the terminology.  Ensure, especially for the poster, that you are considering including simple definitions and explanations - your interpretations will also be critical in understanding the complete story. I am not super familiar with this area, so if you need a test subject, talk with me. 

One area of consideration that I do not see is addressed int he proposal is the approach to the poster presentation. As a team, spend some time storyboarding the poster and consider how such an ambitious project will be translated into a poster.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |      3  |
| Proposal | 5         |    5    |
| Workflow | 1         |    1    |
| Teamwork | 1         |    1  |
| Total    | 10        |   10   |

**Comment by libin-n-g** [comment]
Thanks for the feedback. We will add the poster plan to the proposal. We also have a real-world example that uses an AR model to predict. We will also try to include it as time permits.  

@libin-n-g  @NavyasreeMadhu14 @Saharsh-Bhave @iam-ajeetsingh

**Comment by annahoju** [comment]
Hi Datawaves - I double checked, the 9.75 is a typo.  It should be recorded at 10. 
Best, 
Anna
